# ==============================================================================
#
# Copyright (C) 2022 Sophgo Technologies Inc.  All rights reserved.
#
# TPU-MLIR is licensed under the 2-Clause BSD License except for the
# third-party components.
#
# ==============================================================================
#
# automatically generated by /workspace/tpu-mlir/python/debugger/target_1690e/xlsx_to_py.py
# time: 2025-03-31 03:23:37
# this file should not be changed except format.
# tiu_reg_fn: ./SG2260E tensor_extension_instruction_code_v2.0.13.xlsx
# dma_reg_fn: ./SG2260E tensor_extension_instruction_code_v2.0.13.xlsx

from typing import Dict, Type
import ctypes
from ..target_common import atomic_reg


class sCONV_reg(atomic_reg):
    OP_NAME = "sCONV"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("opt_opd4_const", ctypes.c_uint64, 1),
        ("opt_opd5_const", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("op_code", ctypes.c_uint64, 5),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("pad_mode", ctypes.c_uint64, 2),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_res_add", ctypes.c_uint64, 1),
        ("opt_kernel_rotate", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opd0_up_pad", ctypes.c_uint64, 4),
        ("opd0_dn_pad", ctypes.c_uint64, 4),
        ("opd0_lf_pad", ctypes.c_uint64, 4),
        ("opd0_rt_pad", ctypes.c_uint64, 4),
        ("res_op_x_str", ctypes.c_uint64, 4),
        ("res_op_y_str", ctypes.c_uint64, 4),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("res0_addr", ctypes.c_uint64, 26),
        ("intr_en", ctypes.c_uint64, 1),
        ("opd0_x_ins0", ctypes.c_uint64, 4),
        ("opd0_y_ins0", ctypes.c_uint64, 4),
        ("opd1_x_ins0", ctypes.c_uint64, 4),
        ("opd1_y_ins0", ctypes.c_uint64, 4),
        ("opd0_n_str", ctypes.c_uint64, 16),
        ("opd0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_h", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opd0_c_str", ctypes.c_uint64, 16),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
        ("opd0_h_str", ctypes.c_uint64, 16),
        ("opd0_w_str", ctypes.c_uint64, 16),
        ("imm0", ctypes.c_uint64, 32),
        ("reg_idx0", ctypes.c_uint64, 8),
        ("intr_en", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 3),
        ("reg_idx1", ctypes.c_uint64, 8),
        ("reg_idx2", ctypes.c_uint64, 8),
        ("imm1", ctypes.c_uint64, 64),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_addr", ctypes.c_uint64, 32),
        ("imm0", ctypes.c_uint64, 32),
        ("reg_idx0", ctypes.c_uint64, 8),
        ("intr_en", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 3),
        ("reg_idx1", ctypes.c_uint64, 8),
        ("reg_idx2", ctypes.c_uint64, 8),
        ("imm1", ctypes.c_uint64, 64),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    opt_opd4_const: int
    opt_opd5_const: int
    opt_relu: int
    opt_rq: int
    opd2_n_str: int
    opt_opd1_prec: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    opt_opd2_sign: int
    pad_mode: int
    opt_res0_sign: int
    opt_opd2_prec: int
    pwr_step: int
    opt_res_add: int
    opt_kernel_rotate: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd1_const: int
    opt_opd2_const: int
    opd0_up_pad: int
    opd0_dn_pad: int
    opd0_lf_pad: int
    opd0_rt_pad: int
    res_op_x_str: int
    res_op_y_str: int
    opt_opd3_const: int
    short_opd0_str: int
    res0_addr: int
    intr_en: int
    opd0_x_ins0: int
    opd0_y_ins0: int
    opd1_x_ins0: int
    opd1_y_ins0: int
    opd0_n_str: int
    opd0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_c: int
    opd0_h: int
    opd0_w: int
    opd1_h: int
    opd1_w: int
    opd0_c_str: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    opd3_addr: int
    opd0_h_str: int
    opd0_w_str: int
    imm0: int
    reg_idx0: int
    intr_en: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_idx1: int
    reg_idx2: int
    imm1: int
    opd0_addr: int
    tsk_lane_num: int
    res0_addr: int
    imm0: int
    reg_idx0: int
    intr_en: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_idx1: int
    reg_idx2: int
    imm1: int
    opd0_addr: int
    tsk_lane_num: int
    res0_addr: int

    length: int = 1024



class sCONV_BW_reg(atomic_reg):
    OP_NAME = "sCONV_BW"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("opt_opd4_const", ctypes.c_uint64, 1),
        ("opt_opd5_const", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("op_code", ctypes.c_uint64, 5),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("pad_mode", ctypes.c_uint64, 2),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_res_add", ctypes.c_uint64, 1),
        ("opt_kernel_rotate", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opd0_up_pad", ctypes.c_uint64, 4),
        ("opd0_dn_pad", ctypes.c_uint64, 4),
        ("opd0_lf_pad", ctypes.c_uint64, 4),
        ("opd0_rt_pad", ctypes.c_uint64, 4),
        ("res_op_x_str", ctypes.c_uint64, 4),
        ("res_op_y_str", ctypes.c_uint64, 4),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("res0_addr", ctypes.c_uint64, 26),
        ("intr_en", ctypes.c_uint64, 1),
        ("opd0_x_ins0", ctypes.c_uint64, 4),
        ("opd0_y_ins0", ctypes.c_uint64, 4),
        ("opd1_x_ins0", ctypes.c_uint64, 4),
        ("opd1_y_ins0", ctypes.c_uint64, 4),
        ("opd0_n_str", ctypes.c_uint64, 16),
        ("opd0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_h", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opd0_c_str", ctypes.c_uint64, 16),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
        ("opd0_h_str", ctypes.c_uint64, 16),
        ("opd0_w_str", ctypes.c_uint64, 16),
    ]

    cmd_short: int
    sym_range: int
    opt_opd4_const: int
    opt_opd5_const: int
    opt_relu: int
    opt_rq: int
    opd2_n_str: int
    opt_opd1_prec: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    opt_opd2_sign: int
    pad_mode: int
    opt_res0_sign: int
    opt_opd2_prec: int
    pwr_step: int
    opt_res_add: int
    opt_kernel_rotate: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd1_const: int
    opt_opd2_const: int
    opd0_up_pad: int
    opd0_dn_pad: int
    opd0_lf_pad: int
    opd0_rt_pad: int
    res_op_x_str: int
    res_op_y_str: int
    opt_opd3_const: int
    short_opd0_str: int
    res0_addr: int
    intr_en: int
    opd0_x_ins0: int
    opd0_y_ins0: int
    opd1_x_ins0: int
    opd1_y_ins0: int
    opd0_n_str: int
    opd0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_c: int
    opd0_h: int
    opd0_w: int
    opd1_h: int
    opd1_w: int
    opd0_c_str: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    opd3_addr: int
    opd0_h_str: int
    opd0_w_str: int

    length: int = 512



class sMM_reg(atomic_reg):
    OP_NAME = "sMM"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 1),
        ("rsvd1", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("rsvd2", ctypes.c_uint64, 3),
        ("rsvd3", ctypes.c_uint64, 8),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_res_add", ctypes.c_uint64, 1),
        ("opt_left_tran", ctypes.c_uint64, 1),
        ("opt_opd0_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("rsvd4", ctypes.c_uint64, 1),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("rsvd5", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("rsvd6", ctypes.c_uint64, 20),
        ("rsvd7", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_n", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("rsvd8", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("rsvd9", ctypes.c_uint64, 32),
        ("imm0", ctypes.c_uint64, 32),
        ("reg_idx0", ctypes.c_uint64, 8),
        ("intr_en", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 3),
        ("reg_idx1", ctypes.c_uint64, 8),
        ("reg_idx2", ctypes.c_uint64, 8),
        ("imm1", ctypes.c_uint64, 64),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    rsvd0: int
    rsvd1: int
    opt_relu: int
    opt_rq: int
    rsvd2: int
    rsvd3: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_res_add: int
    opt_left_tran: int
    opt_opd0_const: int
    opt_opd2_const: int
    rsvd4: int
    opt_res0_sign: int
    rsvd5: int
    pwr_step: int
    intr_en: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    opt_opd2_sign: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opd2_n_str: int
    rsvd6: int
    rsvd7: int
    res0_c: int
    res0_w: int
    opd0_n: int
    opd0_c: int
    opd0_w: int
    rsvd8: int
    opd1_w: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    rsvd9: int
    imm0: int
    reg_idx0: int
    intr_en: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_idx1: int
    reg_idx2: int
    imm1: int
    opd0_addr: int
    tsk_lane_num: int
    res0_addr: int

    length: int = 640



class sMM2_reg(atomic_reg):
    OP_NAME = "sMM2"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("opt_opd4_const", ctypes.c_uint64, 1),
        ("opt_opd5_const", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("rsvd1", ctypes.c_uint64, 2),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 2),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd1_c", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_const", ctypes.c_uint64, 1),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_res_add", ctypes.c_uint64, 1),
        ("res0_addr", ctypes.c_uint64, 25),
        ("intr_en", ctypes.c_uint64, 1),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("imm0", ctypes.c_uint64, 32),
        ("reg_idx0", ctypes.c_uint64, 8),
        ("intr_en", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 3),
        ("reg_idx1", ctypes.c_uint64, 8),
        ("reg_idx2", ctypes.c_uint64, 8),
        ("imm1", ctypes.c_uint64, 64),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_addr", ctypes.c_uint64, 32),
        ("imm0", ctypes.c_uint64, 32),
        ("reg_idx0", ctypes.c_uint64, 8),
        ("intr_en", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 3),
        ("reg_idx1", ctypes.c_uint64, 8),
        ("reg_idx2", ctypes.c_uint64, 8),
        ("imm1", ctypes.c_uint64, 64),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    opt_opd4_const: int
    opt_opd5_const: int
    opt_relu: int
    opt_rq: int
    opt_opd2_prec: int
    opt_opd1_prec: int
    rsvd1: int
    opt_opd2_sign: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    opt_res0_prec: int
    opt_res0_sign: int
    opd2_n_str: int
    pwr_step: int
    opt_opd2_const: int
    res0_c: int
    res0_w: int
    opd1_c: int
    opd1_w: int
    opt_opd0_prec: int
    opt_opd0_const: int
    opt_opd1_const: int
    opt_res_add: int
    res0_addr: int
    intr_en: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    imm0: int
    reg_idx0: int
    intr_en: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_idx1: int
    reg_idx2: int
    imm1: int
    opd0_addr: int
    tsk_lane_num: int
    res0_addr: int
    imm0: int
    reg_idx0: int
    intr_en: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_idx1: int
    reg_idx2: int
    imm1: int
    opd0_addr: int
    tsk_lane_num: int
    res0_addr: int

    length: int = 768



class sCMP_reg(atomic_reg):
    OP_NAME = "sCMP"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_const", ctypes.c_uint64, 1),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 2),
        ("rsvd1", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("short_opd1_str", ctypes.c_uint64, 3),
        ("rsvd2", ctypes.c_uint64, 50),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_const: int
    opt_opd1_const: int
    opt_opd2_const: int
    opt_opd3_const: int
    rsvd0: int
    rsvd1: int
    pwr_step: int
    intr_en: int
    opt_opd0_prec: int
    opt_opd2_prec: int
    short_opd0_str: int
    short_opd1_str: int
    rsvd2: int
    opt_opd2_sign: int
    opt_opd0_sign: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    res0_addr: int
    res1_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    opd3_addr: int

    length: int = 384



class sSFU_reg(atomic_reg):
    OP_NAME = "sSFU"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("rsvd0", ctypes.c_uint64, 6),
        ("rsvd1", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd2_n_str", ctypes.c_uint64, 2),
        ("rsvd2", ctypes.c_uint64, 8),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd1_n", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    rsvd0: int
    rsvd1: int
    pwr_step: int
    intr_en: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opd2_n_str: int
    rsvd2: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd1_n: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int

    length: int = 256



class sVC_reg(atomic_reg):
    OP_NAME = "sVC"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("rsvd0", ctypes.c_uint64, 4),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("res0_addr", ctypes.c_uint64, 32),
        ("rsvd1", ctypes.c_uint64, 23),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("rsvd2", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 64),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    opd2_n_str: int
    rsvd0: int
    pwr_step: int
    intr_en: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd1_prec: int
    res0_addr: int
    rsvd1: int
    opd0_addr: int
    rsvd2: int
    res0_c: int
    res0_w: int
    opd0_c: int
    opd0_w: int
    opd1_w: int
    opd1_addr: int
    opd2_addr: int
    rsvd3: int

    length: int = 384



class sLIN_reg(atomic_reg):
    OP_NAME = "sLIN"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_rsv0", ctypes.c_uint64, 29),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd0_sign", ctypes.c_uint64, 1),
        ("opd1_sign", ctypes.c_uint64, 1),
        ("opd2_sign", ctypes.c_uint64, 1),
        ("res0_sign", ctypes.c_uint64, 1),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd1_const: int
    opt_opd2_const: int
    opt_res0_prec: int
    opt_rsv0: int
    opt_opd0_prec: int
    opd0_sign: int
    opd1_sign: int
    opd2_sign: int
    res0_sign: int
    pwr_step: int
    intr_en: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int

    length: int = 288



class sAR_cvt_reg(atomic_reg):
    OP_NAME = "sAR_cvt"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_const", ctypes.c_uint64, 1),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("tsk_opd_num", ctypes.c_uint64, 2),
        ("sym_range", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("short_res0_str", ctypes.c_uint64, 3),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("short_opd1_str", ctypes.c_uint64, 3),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("rsvd1", ctypes.c_uint64, 6),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res0_n_str_15_0", ctypes.c_uint64, 16),
        ("res0_c_str_15_0", ctypes.c_uint64, 16),
        ("opd0_n_str_15_0", ctypes.c_uint64, 16),
        ("opd0_c_str_15_0", ctypes.c_uint64, 16),
        ("opd1_n_str_15_0", ctypes.c_uint64, 16),
        ("opd1_c_str_15_0", ctypes.c_uint64, 16),
        ("res0_h_str", ctypes.c_uint64, 18),
        ("res0_n_str_17_16", ctypes.c_uint64, 2),
        ("res0_w_str", ctypes.c_uint64, 18),
        ("res0_c_str_17_16", ctypes.c_uint64, 2),
        ("opd0_h_str", ctypes.c_uint64, 18),
        ("opd0_n_str_17_16", ctypes.c_uint64, 2),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("rsvd2", ctypes.c_uint64, 3),
        ("opd0_w_str", ctypes.c_uint64, 18),
        ("opd0_c_str_17_16", ctypes.c_uint64, 2),
        ("opd1_h_str", ctypes.c_uint64, 18),
        ("opd1_n_str_17_16", ctypes.c_uint64, 2),
        ("opd1_w_str", ctypes.c_uint64, 18),
        ("opd1_c_str_17_16", ctypes.c_uint64, 2),
        ("rsvd3", ctypes.c_uint64, 4),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_const: int
    opt_opd1_const: int
    opt_opd2_const: int
    tsk_opd_num: int
    sym_range: int
    rsvd0: int
    pwr_step: int
    intr_en: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd1_prec: int
    opt_opd2_prec: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    short_res0_str: int
    short_opd0_str: int
    short_opd1_str: int
    opd2_n_str: int
    rsvd1: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res0_n_str_15_0: int
    res0_c_str_15_0: int
    opd0_n_str_15_0: int
    opd0_c_str_15_0: int
    opd1_n_str_15_0: int
    opd1_c_str_15_0: int
    res0_h_str: int
    res0_n_str_17_16: int
    res0_w_str: int
    res0_c_str_17_16: int
    opd0_h_str: int
    opd0_n_str_17_16: int
    opt_opd2_sign: int
    rsvd2: int
    opd0_w_str: int
    opd0_c_str_17_16: int
    opd1_h_str: int
    opd1_n_str_17_16: int
    opd1_w_str: int
    opd1_c_str_17_16: int
    rsvd3: int

    length: int = 512



class sAR_reg(atomic_reg):
    OP_NAME = "sAR"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_const", ctypes.c_uint64, 1),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("tsk_opd_num", ctypes.c_uint64, 2),
        ("sym_range", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("short_res0_str", ctypes.c_uint64, 3),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("short_opd1_str", ctypes.c_uint64, 3),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("rsvd1", ctypes.c_uint64, 6),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res0_n_str_15_0", ctypes.c_uint64, 16),
        ("res0_c_str_15_0", ctypes.c_uint64, 16),
        ("opd0_n_str_15_0", ctypes.c_uint64, 16),
        ("opd0_c_str_15_0", ctypes.c_uint64, 16),
        ("opd1_n_str_15_0", ctypes.c_uint64, 16),
        ("opd1_c_str_15_0", ctypes.c_uint64, 16),
        ("res0_h_str", ctypes.c_uint64, 18),
        ("res0_n_str_17_16", ctypes.c_uint64, 2),
        ("res0_w_str", ctypes.c_uint64, 18),
        ("res0_c_str_17_16", ctypes.c_uint64, 2),
        ("opd0_h_str", ctypes.c_uint64, 18),
        ("opd0_n_str_17_16", ctypes.c_uint64, 2),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("rsvd2", ctypes.c_uint64, 3),
        ("opd0_w_str", ctypes.c_uint64, 18),
        ("opd0_c_str_17_16", ctypes.c_uint64, 2),
        ("opd1_h_str", ctypes.c_uint64, 18),
        ("opd1_n_str_17_16", ctypes.c_uint64, 2),
        ("opd1_w_str", ctypes.c_uint64, 18),
        ("opd1_c_str_17_16", ctypes.c_uint64, 2),
        ("rsvd3", ctypes.c_uint64, 4),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_const: int
    opt_opd1_const: int
    opt_opd2_const: int
    tsk_opd_num: int
    sym_range: int
    rsvd0: int
    pwr_step: int
    intr_en: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd1_prec: int
    opt_opd2_prec: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    short_res0_str: int
    short_opd0_str: int
    short_opd1_str: int
    opd2_n_str: int
    rsvd1: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res0_n_str_15_0: int
    res0_c_str_15_0: int
    opd0_n_str_15_0: int
    opd0_c_str_15_0: int
    opd1_n_str_15_0: int
    opd1_c_str_15_0: int
    res0_h_str: int
    res0_n_str_17_16: int
    res0_w_str: int
    res0_c_str_17_16: int
    opd0_h_str: int
    opd0_n_str_17_16: int
    opt_opd2_sign: int
    rsvd2: int
    opd0_w_str: int
    opd0_c_str_17_16: int
    opd1_h_str: int
    opd1_n_str_17_16: int
    opd1_w_str: int
    opd1_c_str_17_16: int
    rsvd3: int

    length: int = 512



class sPorD_ROI_reg(atomic_reg):
    OP_NAME = "sPorD_ROI"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 1),
        ("opt_opd5_const", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 11),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_kernel_rotate", ctypes.c_uint64, 1),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("pad_mode", ctypes.c_uint64, 2),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("rsvd1", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd0_x_ins0", ctypes.c_uint64, 4),
        ("opd0_y_ins0", ctypes.c_uint64, 4),
        ("opd1_x_ins0", ctypes.c_uint64, 4),
        ("opd1_y_ins0", ctypes.c_uint64, 4),
        ("opd0_up_pad", ctypes.c_uint64, 4),
        ("opd0_dn_pad", ctypes.c_uint64, 4),
        ("opd0_lf_pad", ctypes.c_uint64, 4),
        ("opd0_rt_pad", ctypes.c_uint64, 4),
        ("res_op_x_str", ctypes.c_uint64, 4),
        ("res_op_y_str", ctypes.c_uint64, 4),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("rsvd2", ctypes.c_uint64, 11),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("intr_en", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_h", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 64),
        ("imm0", ctypes.c_uint64, 32),
        ("reg_idx0", ctypes.c_uint64, 8),
        ("intr_en", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 3),
        ("reg_idx1", ctypes.c_uint64, 8),
        ("reg_idx2", ctypes.c_uint64, 8),
        ("imm1", ctypes.c_uint64, 64),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    rsvd0: int
    opt_opd5_const: int
    opt_relu: int
    opt_rq: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_kernel_rotate: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    pad_mode: int
    opt_res0_sign: int
    rsvd1: int
    pwr_step: int
    opt_opd1_const: int
    opt_opd2_const: int
    opt_opd3_const: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opd0_x_ins0: int
    opd0_y_ins0: int
    opd1_x_ins0: int
    opd1_y_ins0: int
    opd0_up_pad: int
    opd0_dn_pad: int
    opd0_lf_pad: int
    opd0_rt_pad: int
    res_op_x_str: int
    res_op_y_str: int
    opd2_n_str: int
    rsvd2: int
    opt_opd2_sign: int
    intr_en: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_h: int
    opd0_w: int
    opd1_h: int
    opd1_w: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    opd3_addr: int
    rsvd3: int
    imm0: int
    reg_idx0: int
    intr_en: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_idx1: int
    reg_idx2: int
    imm1: int
    opd0_addr: int
    tsk_lane_num: int
    res0_addr: int

    length: int = 768



class sPorD_reg(atomic_reg):
    OP_NAME = "sPorD"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 1),
        ("opt_opd5_const", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 11),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_kernel_rotate", ctypes.c_uint64, 1),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("pad_mode", ctypes.c_uint64, 2),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd0_x_ins0", ctypes.c_uint64, 4),
        ("opd0_y_ins0", ctypes.c_uint64, 4),
        ("opd1_x_ins0", ctypes.c_uint64, 4),
        ("opd1_y_ins0", ctypes.c_uint64, 4),
        ("opd0_up_pad", ctypes.c_uint64, 4),
        ("opd0_dn_pad", ctypes.c_uint64, 4),
        ("opd0_lf_pad", ctypes.c_uint64, 4),
        ("opd0_rt_pad", ctypes.c_uint64, 4),
        ("res_op_x_str", ctypes.c_uint64, 4),
        ("res_op_y_str", ctypes.c_uint64, 4),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("rsvd2", ctypes.c_uint64, 11),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("intr_en", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_h", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 64),
        ("imm0", ctypes.c_uint64, 32),
        ("reg_idx0", ctypes.c_uint64, 8),
        ("intr_en", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 3),
        ("reg_idx1", ctypes.c_uint64, 8),
        ("reg_idx2", ctypes.c_uint64, 8),
        ("imm1", ctypes.c_uint64, 64),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    rsvd0: int
    opt_opd5_const: int
    opt_relu: int
    opt_rq: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_kernel_rotate: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    pad_mode: int
    opt_res0_sign: int
    opt_opd2_prec: int
    pwr_step: int
    opt_opd1_const: int
    opt_opd2_const: int
    opt_opd3_const: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opd0_x_ins0: int
    opd0_y_ins0: int
    opd1_x_ins0: int
    opd1_y_ins0: int
    opd0_up_pad: int
    opd0_dn_pad: int
    opd0_lf_pad: int
    opd0_rt_pad: int
    res_op_x_str: int
    res_op_y_str: int
    opd2_n_str: int
    rsvd2: int
    opt_opd2_sign: int
    intr_en: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_h: int
    opd0_w: int
    opd1_h: int
    opd1_w: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    opd3_addr: int
    rsvd3: int
    imm0: int
    reg_idx0: int
    intr_en: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_idx1: int
    reg_idx2: int
    imm1: int
    opd0_addr: int
    tsk_lane_num: int
    res0_addr: int

    length: int = 768



class sRQDQ_reg(atomic_reg):
    OP_NAME = "sRQDQ"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("rsvd0", ctypes.c_uint64, 4),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd2_n_str", ctypes.c_uint64, 6),
        ("rsvd1", ctypes.c_uint64, 1),
        ("res0_addr", ctypes.c_uint64, 26),
        ("opd0_addr", ctypes.c_uint64, 27),
        ("intr_en", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_opd2_sign: int
    opt_res0_prec: int
    rsvd0: int
    pwr_step: int
    opt_opd1_const: int
    opt_opd0_prec: int
    opd2_n_str: int
    rsvd1: int
    res0_addr: int
    opd0_addr: int
    intr_en: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd1_addr: int
    opd2_addr: int

    length: int = 256



class sSG_reg(atomic_reg):
    OP_NAME = "sSG"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("intr_en", ctypes.c_uint64, 1),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("rsvd0", ctypes.c_uint64, 4),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_c", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("res0_addr", ctypes.c_uint64, 29),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd0_addr", ctypes.c_uint64, 29),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("opd1_addr", ctypes.c_uint64, 29),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd3_const: int
    intr_en: int
    short_opd0_str: int
    rsvd0: int
    pwr_step: int
    opt_opd2_const: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_h: int
    opd0_w: int
    opd1_c: int
    opd1_w: int
    opt_res0_prec: int
    res0_addr: int
    opt_opd0_prec: int
    opd0_addr: int
    opt_opd1_prec: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    opd3_addr: int

    length: int = 384



class sSGL_reg(atomic_reg):
    OP_NAME = "sSGL"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("rsvd0", ctypes.c_uint64, 3),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("intr_en", ctypes.c_uint64, 1),
        ("rsvd1", ctypes.c_uint64, 4),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("rsvd2", ctypes.c_uint64, 7),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 64),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    rsvd0: int
    opt_opd3_const: int
    intr_en: int
    rsvd1: int
    pwr_step: int
    opt_opd2_const: int
    opt_res0_prec: int
    opt_opd1_prec: int
    short_opd0_str: int
    rsvd2: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_h: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    rsvd3: int

    length: int = 384



class sBC_CWT_reg(atomic_reg):
    OP_NAME = "sBC&CWT"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("rsvd0", ctypes.c_uint64, 6),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("rsvd1", ctypes.c_uint64, 32),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_res0_prec: int
    rsvd0: int
    pwr_step: int
    intr_en: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_c: int
    opd0_w: int
    rsvd1: int
    res0_addr: int
    opd0_addr: int

    length: int = 256



class sSYS_reg(atomic_reg):
    OP_NAME = "sSYS"
    _fields_ = [
        ("rsvd0", ctypes.c_uint64, 1),
        ("rsvd1", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("reg_vld", ctypes.c_uint64, 2),
        ("reg_idx", ctypes.c_uint64, 7),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("imm", ctypes.c_uint64, 64),
        ("opt_opd0_prec", ctypes.c_uint64, 2),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("opd0_n", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("opd2_n_str", ctypes.c_uint64, 16),
    ]

    rsvd0: int
    rsvd1: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_vld: int
    reg_idx: int
    pwr_step: int
    intr_en: int
    imm: int
    opt_opd0_prec: int
    short_opd0_str: int
    opd0_n: int
    opd0_c: int
    opd0_h: int
    opd0_w: int
    opd0_addr: int
    tsk_lane_num: int
    opd2_n_str: int

    length: int = 309



class SYS_TR_WR_reg(atomic_reg):
    OP_NAME = "SYS_TR_WR"
    _fields_ = [
        ("imm0", ctypes.c_uint64, 32),
        ("reg_idx0", ctypes.c_uint64, 8),
        ("intr_en", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 3),
        ("reg_idx1", ctypes.c_uint64, 8),
        ("reg_idx2", ctypes.c_uint64, 8),
        ("imm1", ctypes.c_uint64, 64),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_addr", ctypes.c_uint64, 32),
    ]

    imm0: int
    reg_idx0: int
    intr_en: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_idx1: int
    reg_idx2: int
    imm1: int
    opd0_addr: int
    tsk_lane_num: int
    res0_addr: int

    length: int = 256



class sRAND_reg(atomic_reg):
    OP_NAME = "sRAND"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_res_add", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("reserved", ctypes.c_uint64, 5),
        ("reserved", ctypes.c_uint64, 64),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd2_n_str", ctypes.c_uint64, 16),
        ("opd2_c_str", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 64),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    pwr_step: int
    intr_en: int
    opt_res_add: int
    opt_res0_prec: int
    reserved: int
    reserved: int
    res0_c: int
    res0_w: int
    opd2_n_str: int
    opd2_c_str: int
    res0_addr: int
    opd0_addr: int
    res1_addr: int
    reserved: int

    length: int = 384



class DMA_tensor_reg(atomic_reg):
    OP_NAME = "DMA_tensor"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("cache_en", ctypes.c_uint64, 1),
        ("cache_flush", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("bid_in_order", ctypes.c_uint64, 1),
        ("bw_lmt_rd", ctypes.c_uint64, 1),
        ("bw_lmt_wr", ctypes.c_uint64, 1),
        ("early_resp_dis", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 3),
        ("reserved", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_nstride", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("src_wstride", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("dst_wstride", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_nsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 16),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("all_reduce_code", ctypes.c_uint64, 16),
        ("Reserved", ctypes.c_uint64, 16),
        ("Reserved", ctypes.c_uint64, 16),
        ("Reserved", ctypes.c_uint64, 16),
        ("localmem_mask_l32", ctypes.c_uint64, 32),
        ("localmem_mask_h32", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    cache_en: int
    cache_flush: int
    reserved: int
    bid_in_order: int
    bw_lmt_rd: int
    bw_lmt_wr: int
    early_resp_dis: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_nstride: int
    src_cstride: int
    src_hstride: int
    src_wstride: int
    dst_nstride: int
    dst_cstride: int
    dst_hstride: int
    dst_wstride: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    dst_nsize: int
    dst_csize: int
    dst_hsize: int
    dst_wsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    all_reduce_code: int
    Reserved: int
    Reserved: int
    Reserved: int
    localmem_mask_l32: int
    localmem_mask_h32: int

    length: int = 768



class DMA_matrix_reg(atomic_reg):
    OP_NAME = "DMA_matrix"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("cache_en", ctypes.c_uint64, 1),
        ("cache_flush", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("bid_in_order", ctypes.c_uint64, 1),
        ("bw_lmt_rd", ctypes.c_uint64, 1),
        ("bw_lmt_wr", ctypes.c_uint64, 1),
        ("early_resp_dis", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_nstride", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("src_wstride", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("dst_wstride", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_nsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 16),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("Reserved", ctypes.c_uint64, 32),
        ("Reserved", ctypes.c_uint64, 32),
        ("localmem_mask_l32", ctypes.c_uint64, 32),
        ("localmem_mask_h32", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    cache_en: int
    cache_flush: int
    reserved: int
    bid_in_order: int
    bw_lmt_rd: int
    bw_lmt_wr: int
    early_resp_dis: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_nstride: int
    src_cstride: int
    src_hstride: int
    src_wstride: int
    dst_nstride: int
    dst_cstride: int
    dst_hstride: int
    dst_wstride: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    dst_nsize: int
    dst_csize: int
    dst_hsize: int
    dst_wsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    Reserved: int
    Reserved: int
    localmem_mask_l32: int
    localmem_mask_h32: int

    length: int = 768



class DMA_Mask_Select_reg(atomic_reg):
    OP_NAME = "DMA_Mask_Select"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("cache_en", ctypes.c_uint64, 1),
        ("cache_flush", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("bid_in_order", ctypes.c_uint64, 1),
        ("bw_lmt_rd", ctypes.c_uint64, 1),
        ("bw_lmt_wr", ctypes.c_uint64, 1),
        ("early_resp_dis", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("mask_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("src_hsize_h16", ctypes.c_uint64, 16),
        ("src_wsize_h16", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("mask_start_addr_l32", ctypes.c_uint64, 32),
        ("mask_start_addr_h8", ctypes.c_uint64, 32),
        ("localmem_mask_l32", ctypes.c_uint64, 32),
        ("localmem_mask_h32", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    cache_en: int
    cache_flush: int
    reserved: int
    bid_in_order: int
    bw_lmt_rd: int
    bw_lmt_wr: int
    early_resp_dis: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    mask_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    reserved: int
    reserved: int
    src_hsize_h16: int
    src_wsize_h16: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    mask_start_addr_l32: int
    mask_start_addr_h8: int
    localmem_mask_l32: int
    localmem_mask_h32: int

    length: int = 768



class DMA_general_reg(atomic_reg):
    OP_NAME = "DMA_general"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("cache_en", ctypes.c_uint64, 1),
        ("cache_flush", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("bid_in_order", ctypes.c_uint64, 1),
        ("bw_lmt_rd", ctypes.c_uint64, 1),
        ("bw_lmt_wr", ctypes.c_uint64, 1),
        ("early_resp_dis", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_nstride", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("src_wstride", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("dst_wstride", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_nsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 16),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("Reserved", ctypes.c_uint64, 32),
        ("Reserved", ctypes.c_uint64, 32),
        ("localmem_mask_l32", ctypes.c_uint64, 32),
        ("localmem_mask_h32", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    cache_en: int
    cache_flush: int
    reserved: int
    bid_in_order: int
    bw_lmt_rd: int
    bw_lmt_wr: int
    early_resp_dis: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_nstride: int
    src_cstride: int
    src_hstride: int
    src_wstride: int
    dst_nstride: int
    dst_cstride: int
    dst_hstride: int
    dst_wstride: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    dst_nsize: int
    dst_csize: int
    dst_hsize: int
    dst_wsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    Reserved: int
    Reserved: int
    localmem_mask_l32: int
    localmem_mask_h32: int

    length: int = 768



class DMA_Nonzero_reg(atomic_reg):
    OP_NAME = "DMA_Nonzero"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("cache_en", ctypes.c_uint64, 1),
        ("cache_flush", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("bid_in_order", ctypes.c_uint64, 1),
        ("bw_lmt_rd", ctypes.c_uint64, 1),
        ("bw_lmt_wr", ctypes.c_uint64, 1),
        ("early_resp_dis", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("index_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("src_hsize_h16", ctypes.c_uint64, 16),
        ("src_wsize_h16", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("Reserved", ctypes.c_uint64, 32),
        ("Reserved", ctypes.c_uint64, 32),
        ("localmem_mask_l32", ctypes.c_uint64, 32),
        ("localmem_mask_h32", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    cache_en: int
    cache_flush: int
    reserved: int
    bid_in_order: int
    bw_lmt_rd: int
    bw_lmt_wr: int
    early_resp_dis: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    index_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    dst_nstride: int
    reserved: int
    reserved: int
    reserved: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    reserved: int
    reserved: int
    src_hsize_h16: int
    src_wsize_h16: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    Reserved: int
    Reserved: int
    localmem_mask_l32: int
    localmem_mask_h32: int

    length: int = 768



class DMA_sys_reg(atomic_reg):
    OP_NAME = "DMA_sys"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("cache_en", ctypes.c_uint64, 1),
        ("cache_flush", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("bid_in_order", ctypes.c_uint64, 1),
        ("bw_lmt_rd", ctypes.c_uint64, 1),
        ("bw_lmt_wr", ctypes.c_uint64, 1),
        ("early_resp_dis", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("index", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    cache_en: int
    cache_flush: int
    reserved: int
    bid_in_order: int
    bw_lmt_rd: int
    bw_lmt_wr: int
    early_resp_dis: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    index: int
    constant_value: int

    length: int = 128



class DMA_gather_scatter_reg(atomic_reg):
    OP_NAME = "DMA_gather_scatter"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("cache_en", ctypes.c_uint64, 1),
        ("cache_flush", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("bid_in_order", ctypes.c_uint64, 1),
        ("bw_lmt_rd", ctypes.c_uint64, 1),
        ("bw_lmt_wr", ctypes.c_uint64, 1),
        ("early_resp_dis", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("index_cstride", ctypes.c_uint64, 32),
        ("start_pos", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 32),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 32),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("index_csize", ctypes.c_uint64, 16),
        ("index_hsize", ctypes.c_uint64, 32),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("index_start_addr_l32", ctypes.c_uint64, 32),
        ("index_start_addr_h13", ctypes.c_uint64, 13),
        ("reserve", ctypes.c_uint64, 19),
        ("localmem_mask_l32", ctypes.c_uint64, 32),
        ("localmem_mask_h32", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    cache_en: int
    cache_flush: int
    reserved: int
    bid_in_order: int
    bw_lmt_rd: int
    bw_lmt_wr: int
    early_resp_dis: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_cstride: int
    src_hstride: int
    dst_cstride: int
    dst_hstride: int
    index_cstride: int
    start_pos: int
    reserved: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    dst_csize: int
    dst_hsize: int
    dst_wsize: int
    index_csize: int
    index_hsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    index_start_addr_l32: int
    index_start_addr_h13: int
    reserve: int
    localmem_mask_l32: int
    localmem_mask_h32: int

    length: int = 768



class DMA_Reverse_reg(atomic_reg):
    OP_NAME = "DMA_Reverse"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("cache_en", ctypes.c_uint64, 1),
        ("cache_flush", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("bid_in_order", ctypes.c_uint64, 1),
        ("bw_lmt_rd", ctypes.c_uint64, 1),
        ("bw_lmt_wr", ctypes.c_uint64, 1),
        ("early_resp_dis", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_nstride", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("src_wstride", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("dst_wstride", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_nsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 16),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("Reserved", ctypes.c_uint64, 32),
        ("Reserved", ctypes.c_uint64, 32),
        ("localmem_mask_l32", ctypes.c_uint64, 32),
        ("localmem_mask_h32", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    cache_en: int
    cache_flush: int
    reserved: int
    bid_in_order: int
    bw_lmt_rd: int
    bw_lmt_wr: int
    early_resp_dis: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_nstride: int
    src_cstride: int
    src_hstride: int
    src_wstride: int
    dst_nstride: int
    dst_cstride: int
    dst_hstride: int
    dst_wstride: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    dst_nsize: int
    dst_csize: int
    dst_hsize: int
    dst_wsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    Reserved: int
    Reserved: int
    localmem_mask_l32: int
    localmem_mask_h32: int

    length: int = 768



class DMA_Lossy_compress_reg(atomic_reg):
    OP_NAME = "DMA_Lossy_compress"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("cache_en", ctypes.c_uint64, 1),
        ("cache_flush", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("bid_in_order", ctypes.c_uint64, 1),
        ("bw_lmt_rd", ctypes.c_uint64, 1),
        ("bw_lmt_wr", ctypes.c_uint64, 1),
        ("early_resp_dis", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 3),
        ("reserved", ctypes.c_uint64, 20),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_nstride", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_nsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 16),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("all_reduce_code", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    cache_en: int
    cache_flush: int
    reserved: int
    bid_in_order: int
    bw_lmt_rd: int
    bw_lmt_wr: int
    early_resp_dis: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    reserved: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_nstride: int
    src_cstride: int
    src_hstride: int
    dst_nstride: int
    dst_cstride: int
    dst_hstride: int
    reserved: int
    reserved: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    dst_nsize: int
    dst_csize: int
    dst_hsize: int
    dst_wsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    all_reduce_code: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int

    length: int = 768

class sCDMA_sys_reg(atomic_reg):
    OP_NAME = "sCDMA_sys"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("cmd_type", ctypes.c_uint64, 4),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("reserved", ctypes.c_uint64, 21), # 32bit
        ("constant_value_l32", ctypes.c_uint64, 32),
        ("constant_value_h32", ctypes.c_uint64, 32),
        ("reg_sel", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 28),
    ]

    intr_en: int
    stride_enable: int
    reserved: int
    cmd_type: int
    cmd_special_function: int
    reserved: int
    constant_value_l32: int
    constant_value_h32: int
    reg_sel: int
    reserved: int

    length: int = 128

op_class_dic: Dict[str, Type[atomic_reg]] = {

    "sCONV": sCONV_reg,
    "sCONV_BW": sCONV_BW_reg,
    "sMM": sMM_reg,
    "sMM2": sMM2_reg,
    "sCMP": sCMP_reg,
    "sSFU": sSFU_reg,
    "sVC": sVC_reg,
    "sLIN": sLIN_reg,
    "sAR_cvt": sAR_cvt_reg,
    "sAR": sAR_reg,
    "sPorD_ROI": sPorD_ROI_reg,
    "sPorD": sPorD_reg,
    "sRQDQ": sRQDQ_reg,
    "sSG": sSG_reg,
    "sSGL": sSGL_reg,
    "sBC&CWT": sBC_CWT_reg,
    "sSYS": sSYS_reg,
    "SYS_TR_WR": SYS_TR_WR_reg,
    "sRAND": sRAND_reg,
    "DMA_tensor": DMA_tensor_reg,
    "DMA_matrix": DMA_matrix_reg,
    "DMA_Mask_Select": DMA_Mask_Select_reg,
    "DMA_general": DMA_general_reg,
    "DMA_Nonzero": DMA_Nonzero_reg,
    "DMA_sys": DMA_sys_reg,
    "DMA_gather_scatter": DMA_gather_scatter_reg,
    "DMA_Reverse": DMA_Reverse_reg,
    "DMA_Lossy_compress": DMA_Lossy_compress_reg,
    "sCDMA_sys": sCDMA_sys_reg,
}
