# ==============================================================================
#
# Copyright (C) 2022 Sophgo Technologies Inc.  All rights reserved.
#
# TPU-MLIR is licensed under the 2-Clause BSD License except for the
# third-party components.
#
# ==============================================================================
#
# automatically generated by /home/hanqing/workspace/tpu-mlir/python/debugger/target_1684x2/xlsx_to_py.py
# time: 2025-12-11 15:40:15
# this file should not be changed except format.
# tiu_reg_fn: ./BM1684x2_Regs.xlsx
# dma_reg_fn: ./BM1684x2_Regs.xlsx

from typing import Dict, Type
import ctypes
from ..target_common import atomic_reg


class sCONV_reg(atomic_reg):
    OP_NAME = "sCONV"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("opt_opd4_const", ctypes.c_uint64, 1),
        ("opt_opd5_const", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("op_code", ctypes.c_uint64, 5),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("pad_mode", ctypes.c_uint64, 2),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_res_add", ctypes.c_uint64, 1),
        ("opt_kernel_rotate", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opd0_up_pad", ctypes.c_uint64, 4),
        ("opd0_dn_pad", ctypes.c_uint64, 4),
        ("opd0_lf_pad", ctypes.c_uint64, 4),
        ("opd0_rt_pad", ctypes.c_uint64, 4),
        ("res_op_x_str", ctypes.c_uint64, 4),
        ("res_op_y_str", ctypes.c_uint64, 4),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("res0_addr", ctypes.c_uint64, 26),
        ("intr_en", ctypes.c_uint64, 1),
        ("opd0_x_ins0", ctypes.c_uint64, 4),
        ("opd0_y_ins0", ctypes.c_uint64, 4),
        ("opd1_x_ins0", ctypes.c_uint64, 4),
        ("opd1_y_ins0", ctypes.c_uint64, 4),
        ("opd0_n_str", ctypes.c_uint64, 16),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_h", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opd0_c_str", ctypes.c_uint64, 16),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
        ("opd0_h_str", ctypes.c_uint64, 16),
        ("opd0_w_str", ctypes.c_uint64, 16),
    ]

    cmd_short: int
    sym_range: int
    opt_opd4_const: int
    opt_opd5_const: int
    opt_relu: int
    opt_rq: int
    opd2_n_str: int
    opt_opd1_prec: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    opt_opd2_sign: int
    pad_mode: int
    opt_res0_sign: int
    opt_opd2_prec: int
    pwr_step: int
    opt_res_add: int
    opt_kernel_rotate: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd1_const: int
    opt_opd2_const: int
    opd0_up_pad: int
    opd0_dn_pad: int
    opd0_lf_pad: int
    opd0_rt_pad: int
    res_op_x_str: int
    res_op_y_str: int
    opt_opd3_const: int
    short_opd0_str: int
    res0_addr: int
    intr_en: int
    opd0_x_ins0: int
    opd0_y_ins0: int
    opd1_x_ins0: int
    opd1_y_ins0: int
    opd0_n_str: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_c: int
    opd0_h: int
    opd0_w: int
    opd1_h: int
    opd1_w: int
    opd0_c_str: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    opd3_addr: int
    opd0_h_str: int
    opd0_w_str: int

    length: int = 512


class sCONV_DW_reg(atomic_reg):
    OP_NAME = "sCONV_DW"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("opt_opd4_const", ctypes.c_uint64, 1),
        ("opt_opd5_const", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("op_code", ctypes.c_uint64, 5),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("pad_mode", ctypes.c_uint64, 2),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_res_add", ctypes.c_uint64, 1),
        ("opt_kernel_rotate", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opd0_up_pad", ctypes.c_uint64, 4),
        ("opd0_dn_pad", ctypes.c_uint64, 4),
        ("opd0_lf_pad", ctypes.c_uint64, 4),
        ("opd0_rt_pad", ctypes.c_uint64, 4),
        ("res_op_x_str", ctypes.c_uint64, 4),
        ("res_op_y_str", ctypes.c_uint64, 4),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("res0_addr", ctypes.c_uint64, 26),
        ("intr_en", ctypes.c_uint64, 1),
        ("opd0_x_ins0", ctypes.c_uint64, 4),
        ("opd0_y_ins0", ctypes.c_uint64, 4),
        ("opd1_x_ins0", ctypes.c_uint64, 4),
        ("opd1_y_ins0", ctypes.c_uint64, 4),
        ("opd0_n_str", ctypes.c_uint64, 16),
        ("opd0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_h", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opd0_c_str", ctypes.c_uint64, 16),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
        ("opd0_h_str", ctypes.c_uint64, 16),
        ("opd0_w_str", ctypes.c_uint64, 16),
    ]

    cmd_short: int
    sym_range: int
    opt_opd4_const: int
    opt_opd5_const: int
    opt_relu: int
    opt_rq: int
    opd2_n_str: int
    opt_opd1_prec: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    opt_opd2_sign: int
    pad_mode: int
    opt_res0_sign: int
    opt_opd2_prec: int
    pwr_step: int
    opt_res_add: int
    opt_kernel_rotate: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd1_const: int
    opt_opd2_const: int
    opd0_up_pad: int
    opd0_dn_pad: int
    opd0_lf_pad: int
    opd0_rt_pad: int
    res_op_x_str: int
    res_op_y_str: int
    opt_opd3_const: int
    short_opd0_str: int
    res0_addr: int
    intr_en: int
    opd0_x_ins0: int
    opd0_y_ins0: int
    opd1_x_ins0: int
    opd1_y_ins0: int
    opd0_n_str: int
    opd0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_c: int
    opd0_h: int
    opd0_w: int
    opd1_h: int
    opd1_w: int
    opd0_c_str: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    opd3_addr: int
    opd0_h_str: int
    opd0_w_str: int

    length: int = 512


class sPorD_reg(atomic_reg):
    OP_NAME = "sPorD"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 1),
        ("opt_opd5_const", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 11),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_kernel_rotate", ctypes.c_uint64, 1),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("pad_mode", ctypes.c_uint64, 2),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd0_x_ins0", ctypes.c_uint64, 4),
        ("opd0_y_ins0", ctypes.c_uint64, 4),
        ("opd1_x_ins0", ctypes.c_uint64, 4),
        ("opd1_y_ins0", ctypes.c_uint64, 4),
        ("opd0_up_pad", ctypes.c_uint64, 4),
        ("opd0_dn_pad", ctypes.c_uint64, 4),
        ("opd0_lf_pad", ctypes.c_uint64, 4),
        ("opd0_rt_pad", ctypes.c_uint64, 4),
        ("res_op_x_str", ctypes.c_uint64, 4),
        ("res_op_y_str", ctypes.c_uint64, 4),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("rsvd2", ctypes.c_uint64, 11),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("intr_en", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_h", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 64),
    ]

    cmd_short: int
    sym_range: int
    rsvd0: int
    opt_opd5_const: int
    opt_relu: int
    opt_rq: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_kernel_rotate: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    pad_mode: int
    opt_res0_sign: int
    opt_opd2_prec: int
    pwr_step: int
    opt_opd1_const: int
    opt_opd2_const: int
    opt_opd3_const: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opd0_x_ins0: int
    opd0_y_ins0: int
    opd1_x_ins0: int
    opd1_y_ins0: int
    opd0_up_pad: int
    opd0_dn_pad: int
    opd0_lf_pad: int
    opd0_rt_pad: int
    res_op_x_str: int
    res_op_y_str: int
    opd2_n_str: int
    rsvd2: int
    opt_opd2_sign: int
    intr_en: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_h: int
    opd0_w: int
    opd1_h: int
    opd1_w: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    opd3_addr: int
    rsvd3: int

    length: int = 512


class sMM2_reg(atomic_reg):
    OP_NAME = "sMM2"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("opt_opd4_const", ctypes.c_uint64, 1),
        ("opt_opd5_const", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_rq", ctypes.c_uint64, 1),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("rsvd1", ctypes.c_uint64, 2),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 2),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd1_c", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_const", ctypes.c_uint64, 1),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_res_add", ctypes.c_uint64, 1),
        ("res0_addr", ctypes.c_uint64, 25),
        ("intr_en", ctypes.c_uint64, 1),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    opt_opd4_const: int
    opt_opd5_const: int
    opt_relu: int
    opt_rq: int
    opt_opd2_prec: int
    opt_opd1_prec: int
    rsvd1: int
    opt_opd2_sign: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    opt_res0_prec: int
    opt_res0_sign: int
    opd2_n_str: int
    pwr_step: int
    opt_opd2_const: int
    res0_c: int
    res0_w: int
    opd1_c: int
    opd1_w: int
    opt_opd0_prec: int
    opt_opd0_const: int
    opt_opd1_const: int
    opt_res_add: int
    res0_addr: int
    intr_en: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int

    length: int = 256


class sRQ_sDQ_reg(atomic_reg):
    OP_NAME = "sRQ&sDQ"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("rsvd0", ctypes.c_uint64, 1),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd2_n_str", ctypes.c_uint64, 6),
        ("rsvd1", ctypes.c_uint64, 1),
        ("res0_addr", ctypes.c_uint64, 26),
        ("opd0_addr", ctypes.c_uint64, 27),
        ("intr_en", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 64),
        ("rsvd3_1", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_res0_sign: int
    opt_res0_prec: int
    rsvd0: int
    short_opd0_str: int
    pwr_step: int
    opt_opd1_const: int
    opt_opd0_prec: int
    opd2_n_str: int
    rsvd1: int
    res0_addr: int
    opd0_addr: int
    intr_en: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    rsvd3: int

    length: int = 384


class sAR_reg(atomic_reg):
    OP_NAME = "sAR"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_const", ctypes.c_uint64, 1),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("tsk_opd_num", ctypes.c_uint64, 2),
        ("sym_range", ctypes.c_uint64, 1),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 2),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("short_res0_str", ctypes.c_uint64, 3),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("short_opd1_str", ctypes.c_uint64, 3),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("rsvd1", ctypes.c_uint64, 6),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res0_n_str", ctypes.c_uint64, 18),
        ("res0_c_str", ctypes.c_uint64, 18),
        ("opd0_n_str", ctypes.c_uint64, 18),
        ("opd0_c_str", ctypes.c_uint64, 18),
        ("opd1_n_str", ctypes.c_uint64, 18),
        ("opd1_c_str", ctypes.c_uint64, 18),
        ("res0_h_str", ctypes.c_uint64, 18),
        ("res0_w_str", ctypes.c_uint64, 18),
        ("opd0_h_str", ctypes.c_uint64, 18),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("rsvd2", ctypes.c_uint64, 3),
        ("opd0_w_str", ctypes.c_uint64, 18),
        ("opd1_h_str", ctypes.c_uint64, 18),
        ("opd1_w_str", ctypes.c_uint64, 18),
        ("rsvd3", ctypes.c_uint64, 4),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_const: int
    opt_opd1_const: int
    opt_opd2_const: int
    tsk_opd_num: int
    sym_range: int
    opt_res0_sign: int
    rsvd0: int
    pwr_step: int
    intr_en: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd1_prec: int
    opt_opd2_prec: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    short_res0_str: int
    short_opd0_str: int
    short_opd1_str: int
    opd2_n_str: int
    rsvd1: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res0_n_str: int
    res0_c_str: int
    opd0_n_str: int
    opd0_c_str: int
    opd1_n_str: int
    opd1_c_str: int
    res0_h_str: int
    res0_w_str: int
    opd0_h_str: int
    opt_opd2_sign: int
    rsvd2: int
    opd0_w_str: int
    opd1_h_str: int
    opd1_w_str: int
    rsvd3: int

    length: int = 512


class sSG_reg(atomic_reg):
    OP_NAME = "sSG"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("intr_en", ctypes.c_uint64, 1),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("rsvd0", ctypes.c_uint64, 4),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_c", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("res0_addr", ctypes.c_uint64, 29),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd0_addr", ctypes.c_uint64, 29),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("opd1_addr", ctypes.c_uint64, 29),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd3_const: int
    intr_en: int
    short_opd0_str: int
    rsvd0: int
    pwr_step: int
    opt_opd2_const: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_h: int
    opd0_w: int
    opd1_c: int
    opd1_w: int
    opt_res0_prec: int
    res0_addr: int
    opt_opd0_prec: int
    opd0_addr: int
    opt_opd1_prec: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    opd3_addr: int

    length: int = 384


class sSGL_reg(atomic_reg):
    OP_NAME = "sSGL"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("rsvd0", ctypes.c_uint64, 3),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("intr_en", ctypes.c_uint64, 1),
        ("rsvd1", ctypes.c_uint64, 4),
        ("pwr_step", ctypes.c_uint64, 4),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("rsvd2", ctypes.c_uint64, 7),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 64),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    rsvd0: int
    opt_opd3_const: int
    intr_en: int
    rsvd1: int
    pwr_step: int
    opt_opd2_const: int
    opt_res0_prec: int
    opt_opd1_prec: int
    short_opd0_str: int
    rsvd2: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_h: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    res1_addr: int
    rsvd3: int

    length: int = 384


class sCW_sBC_reg(atomic_reg):
    OP_NAME = "sCW&sBC"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("rsvd0", ctypes.c_uint64, 6),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("rsvd1", ctypes.c_uint64, 32),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_res0_prec: int
    rsvd0: int
    pwr_step: int
    intr_en: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_c: int
    opd0_w: int
    rsvd1: int
    res0_addr: int
    opd0_addr: int

    length: int = 256


class sPRNG_reg(atomic_reg):
    OP_NAME = "sPRNG"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_res_add", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("rsvd0", ctypes.c_uint64, 5),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd2_n_str", ctypes.c_uint64, 16),
        ("opd2_c_str", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("rsvd2", ctypes.c_uint64, 64),
        ("rsvd2_1", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    pwr_step: int
    intr_en: int
    opt_res_add: int
    opt_res0_prec: int
    rsvd0: int
    tsk_lane_num: int
    res0_c: int
    res0_w: int
    opd2_n_str: int
    opd2_c_str: int
    res0_addr: int
    opd0_addr: int
    res1_addr: int
    rsvd2: int

    length: int = 384


class sSFU_reg(atomic_reg):
    OP_NAME = "sSFU"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 4),
        ("rsvd1", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opd2_n_str", ctypes.c_uint64, 2),
        ("short_opd1_str", ctypes.c_uint64, 3),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("rsvd2", ctypes.c_uint64, 4),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd1_n", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("opd1_n_str", ctypes.c_uint64, 16),
        ("opd1_c_str", ctypes.c_uint64, 16),
        ("opd1_h_str", ctypes.c_uint64, 16),
        ("opd1_w_str", ctypes.c_uint64, 16),
        ("opd3_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 64),
        ("rsvd3_1", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_res0_sign: int
    opt_opd0_sign: int
    rsvd0: int
    rsvd1: int
    pwr_step: int
    intr_en: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opd2_n_str: int
    short_opd1_str: int
    opt_opd1_const: int
    rsvd2: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd1_n: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    res1_addr: int
    opd2_addr: int
    opd1_n_str: int
    opd1_c_str: int
    opd1_h_str: int
    opd1_w_str: int
    opd3_addr: int
    rsvd3: int

    length: int = 512


class sLIN_reg(atomic_reg):
    OP_NAME = "sLIN"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_rsvd0", ctypes.c_uint64, 18),
        ("short_opd1_str", ctypes.c_uint64, 3),
        ("opt_rsvd1", ctypes.c_uint64, 8),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("rsvd3", ctypes.c_uint64, 2),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("opd1_n", ctypes.c_uint64, 16),
        ("opd1_c", ctypes.c_uint64, 16),
        ("opd1_h", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("rsvd2", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd1_const: int
    opt_opd2_const: int
    opt_res0_prec: int
    opt_rsvd0: int
    short_opd1_str: int
    opt_rsvd1: int
    opt_opd0_prec: int
    opt_opd0_sign: int
    opt_res0_sign: int
    rsvd3: int
    pwr_step: int
    intr_en: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    res0_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    opd1_n: int
    opd1_c: int
    opd1_h: int
    opd1_w: int
    rsvd2: int

    length: int = 384


class sREDUCE_reg(atomic_reg):
    OP_NAME = "sREDUCE"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 9),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_relu", ctypes.c_uint64, 1),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_const", ctypes.c_uint64, 1),
        ("short_res0_str", ctypes.c_uint64, 3),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_n", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_h", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("rsvd2", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 32),
    ]

    cmd_short: int
    sym_range: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_res0_sign: int
    rsvd0: int
    pwr_step: int
    intr_en: int
    opt_relu: int
    opt_opd0_sign: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd0_const: int
    short_res0_str: int
    short_opd0_str: int
    tsk_lane_num: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    opd0_n: int
    opd0_c: int
    opd0_h: int
    opd0_w: int
    rsvd2: int
    res0_addr: int
    opd0_addr: int
    rsvd3: int

    length: int = 384


class SYS_TR_WR_reg(atomic_reg):
    OP_NAME = "SYS_TR_WR"
    _fields_ = [
        ("imm0", ctypes.c_uint64, 32),
        ("reg_idx0", ctypes.c_uint64, 8),
        ("intr_en", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 3),
        ("reg_idx1", ctypes.c_uint64, 8),
        ("reg_idx2", ctypes.c_uint64, 8),
        ("imm1", ctypes.c_uint64, 64),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("tsk_lane_num", ctypes.c_uint64, 64),
        ("res0_addr", ctypes.c_uint64, 32),
    ]

    imm0: int
    reg_idx0: int
    intr_en: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_idx1: int
    reg_idx2: int
    imm1: int
    opd0_addr: int
    tsk_lane_num: int
    res0_addr: int

    length: int = 256


class sCMP_reg(atomic_reg):
    OP_NAME = "sCMP"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("sym_range", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_const", ctypes.c_uint64, 1),
        ("opt_opd1_const", ctypes.c_uint64, 1),
        ("opt_opd2_const", ctypes.c_uint64, 1),
        ("opt_opd3_const", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 2),
        ("rsvd1", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd2_prec", ctypes.c_uint64, 3),
        ("short_opd0_str", ctypes.c_uint64, 3),
        ("short_opd1_str", ctypes.c_uint64, 3),
        ("rsvd2", ctypes.c_uint64, 50),
        ("opt_opd2_sign", ctypes.c_uint64, 1),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("res0_n", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_h", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("res0_addr", ctypes.c_uint64, 32),
        ("res1_addr", ctypes.c_uint64, 32),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("opd3_addr", ctypes.c_uint64, 32),
        ("opd1_n_str", ctypes.c_uint64, 16),
        ("opd1_c_str", ctypes.c_uint64, 16),
        ("opd1_h_str", ctypes.c_uint64, 16),
        ("opd1_w_str", ctypes.c_uint64, 16),
        ("rsvd3", ctypes.c_uint64, 64),
    ]

    cmd_short: int
    sym_range: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_const: int
    opt_opd1_const: int
    opt_opd2_const: int
    opt_opd3_const: int
    rsvd0: int
    rsvd1: int
    pwr_step: int
    intr_en: int
    opt_opd0_prec: int
    opt_opd2_prec: int
    short_opd0_str: int
    short_opd1_str: int
    rsvd2: int
    opt_opd2_sign: int
    opt_opd0_sign: int
    res0_n: int
    res0_c: int
    res0_h: int
    res0_w: int
    res0_addr: int
    res1_addr: int
    opd0_addr: int
    opd1_addr: int
    opd2_addr: int
    opd3_addr: int
    opd1_n_str: int
    opd1_c_str: int
    opd1_h_str: int
    opd1_w_str: int
    rsvd3: int

    length: int = 512


class sVC_reg(atomic_reg):
    OP_NAME = "sVC"
    _fields_ = [
        ("cmd_short", ctypes.c_uint64, 1),
        ("op_code", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("opt_opd0_sign", ctypes.c_uint64, 1),
        ("opt_opd1_sign", ctypes.c_uint64, 1),
        ("opd2_n_str", ctypes.c_uint64, 3),
        ("opt_res0_sign", ctypes.c_uint64, 1),
        ("rsvd0", ctypes.c_uint64, 3),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("opt_res0_prec", ctypes.c_uint64, 3),
        ("opt_opd0_prec", ctypes.c_uint64, 3),
        ("opt_opd1_prec", ctypes.c_uint64, 3),
        ("res0_addr", ctypes.c_uint64, 32),
        ("rsvd1", ctypes.c_uint64, 23),
        ("opd0_addr", ctypes.c_uint64, 32),
        ("rsvd2", ctypes.c_uint64, 16),
        ("res0_c", ctypes.c_uint64, 16),
        ("res0_w", ctypes.c_uint64, 16),
        ("opd0_c", ctypes.c_uint64, 16),
        ("opd0_w", ctypes.c_uint64, 16),
        ("opd1_w", ctypes.c_uint64, 16),
        ("opd1_addr", ctypes.c_uint64, 32),
        ("opd2_addr", ctypes.c_uint64, 32),
        ("rsvd3", ctypes.c_uint64, 64),
    ]

    cmd_short: int
    op_code: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    opt_opd0_sign: int
    opt_opd1_sign: int
    opd2_n_str: int
    opt_res0_sign: int
    rsvd0: int
    pwr_step: int
    intr_en: int
    opt_res0_prec: int
    opt_opd0_prec: int
    opt_opd1_prec: int
    res0_addr: int
    rsvd1: int
    opd0_addr: int
    rsvd2: int
    res0_c: int
    res0_w: int
    opd0_c: int
    opd0_w: int
    opd1_w: int
    opd1_addr: int
    opd2_addr: int
    rsvd3: int

    length: int = 384


class SYS_reg(atomic_reg):
    OP_NAME = "SYS"
    _fields_ = [
        ("rsvd0", ctypes.c_uint64, 1),
        ("rsvd1", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 23),
        ("dbg_mode", ctypes.c_uint64, 1),
        ("tsk_typ", ctypes.c_uint64, 4),
        ("tsk_eu_typ", ctypes.c_uint64, 5),
        ("reg_vld", ctypes.c_uint64, 2),
        ("reg_idx", ctypes.c_uint64, 7),
        ("pwr_step", ctypes.c_uint64, 4),
        ("intr_en", ctypes.c_uint64, 1),
        ("imm", ctypes.c_uint64, 64),
    ]

    rsvd0: int
    rsvd1: int
    cmd_id_dep: int
    dbg_mode: int
    tsk_typ: int
    tsk_eu_typ: int
    reg_vld: int
    reg_idx: int
    pwr_step: int
    intr_en: int
    imm: int

    length: int = 128


class DMA_tensor_reg(atomic_reg):
    OP_NAME = "DMA_tensor"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 3),
        ("reserved", ctypes.c_uint64, 16),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_nstride", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("src_wstride", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("dst_wstride", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_nsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 16),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("reduce_enable", ctypes.c_uint64, 1),
        ("reduce_opcode", ctypes.c_uint64, 3),
        ("reduce_op_sum", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 11),
        ("scale_const_val", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("default_lanemask1", ctypes.c_uint64, 32),
        ("default_lanemask2", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_nstride: int
    src_cstride: int
    src_hstride: int
    src_wstride: int
    dst_nstride: int
    dst_cstride: int
    dst_hstride: int
    dst_wstride: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    dst_nsize: int
    dst_csize: int
    dst_hsize: int
    dst_wsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    reduce_enable: int
    reduce_opcode: int
    reduce_op_sum: int
    reserved: int
    scale_const_val: int
    reserved: int
    reserved: int
    default_lanemask1: int
    default_lanemask2: int

    length: int = 768


class DMA_matrix_reg(atomic_reg):
    OP_NAME = "DMA_matrix"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_nstride", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("src_wstride", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("dst_wstride", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_nsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 16),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("default_lanemask1", ctypes.c_uint64, 32),
        ("default_lanemask2", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_nstride: int
    src_cstride: int
    src_hstride: int
    src_wstride: int
    dst_nstride: int
    dst_cstride: int
    dst_hstride: int
    dst_wstride: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    dst_nsize: int
    dst_csize: int
    dst_hsize: int
    dst_wsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    reserved: int
    reserved: int
    default_lanemask1: int
    default_lanemask2: int

    length: int = 768


class DMA_masked_select_reg(atomic_reg):
    OP_NAME = "DMA_masked_select"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("mask_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("src_hsize_h16", ctypes.c_uint64, 16),
        ("src_wsize_h16", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("mask_start_addr_l32", ctypes.c_uint64, 32),
        ("mask_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("default_lanemask1", ctypes.c_uint64, 32),
        ("default_lanemask2", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    mask_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    reserved: int
    reserved: int
    src_hsize_h16: int
    src_wsize_h16: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    mask_start_addr_l32: int
    mask_start_addr_h13: int
    reserved: int
    default_lanemask1: int
    default_lanemask2: int

    length: int = 768


class DMA_general_reg(atomic_reg):
    OP_NAME = "DMA_general"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_nstride", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("src_wstride", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("dst_wstride", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize_l16", ctypes.c_uint64, 16),
        ("dst_nsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 16),
        ("src_wsize_h16", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("default_lanemask1", ctypes.c_uint64, 32),
        ("default_lanemask2", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_nstride: int
    src_cstride: int
    src_hstride: int
    src_wstride: int
    dst_nstride: int
    dst_cstride: int
    dst_hstride: int
    dst_wstride: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize_l16: int
    dst_nsize: int
    dst_csize: int
    dst_hsize: int
    src_wsize_h16: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    reserved: int
    reserved: int
    default_lanemask1: int
    default_lanemask2: int

    length: int = 768


class DMA_nonzero_reg(atomic_reg):
    OP_NAME = "DMA_nonzero"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("index_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 15),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("base_i", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("reserved", ctypes.c_uint64, 16),
        ("src_hsize_h16", ctypes.c_uint64, 16),
        ("src_wsize_h16", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("default_lanemask1", ctypes.c_uint64, 32),
        ("default_lanemask2", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    index_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    base_i: int
    reserved: int
    reserved: int
    reserved: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    reserved: int
    reserved: int
    src_hsize_h16: int
    src_wsize_h16: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    reserved: int
    reserved: int
    default_lanemask1: int
    default_lanemask2: int

    length: int = 768


class sDMA_sys_reg(atomic_reg):
    OP_NAME = "sDMA_sys"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("Reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    Reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int

    length: int = 128


class DMA_gather_reg(atomic_reg):
    OP_NAME = "DMA_gather"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride_or_src_csize_h16", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride_or_dst_csize_h16", ctypes.c_uint64, 32),
        ("index_cstride", ctypes.c_uint64, 32),
        ("start_point", ctypes.c_uint64, 32),
        ("index_csize_h16", ctypes.c_uint64, 16),
        ("src_csize_or_src_csize_l16", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 32),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_csize_or_dst_csize_l16", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 32),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("index_csize_l16", ctypes.c_uint64, 16),
        ("index_hsize", ctypes.c_uint64, 32),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("index_start_addr_l32", ctypes.c_uint64, 32),
        ("index_start_addr_h13", ctypes.c_uint64, 13),
        ("reserve", ctypes.c_uint64, 19),
        ("default_lanemask1", ctypes.c_uint64, 32),
        ("default_lanemask2", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_cstride: int
    src_hstride_or_src_csize_h16: int
    dst_cstride: int
    dst_hstride_or_dst_csize_h16: int
    index_cstride: int
    start_point: int
    index_csize_h16: int
    src_csize_or_src_csize_l16: int
    src_hsize: int
    src_wsize: int
    dst_csize_or_dst_csize_l16: int
    dst_hsize: int
    dst_wsize: int
    index_csize_l16: int
    index_hsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    index_start_addr_l32: int
    index_start_addr_h13: int
    reserve: int
    default_lanemask1: int
    default_lanemask2: int

    length: int = 768


class DMA_scatter_reg(atomic_reg):
    OP_NAME = "DMA_scatter"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride_or_src_csize_h16", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride_or_dst_csize_h16", ctypes.c_uint64, 32),
        ("index_cstride", ctypes.c_uint64, 32),
        ("start_point", ctypes.c_uint64, 32),
        ("index_csize_h16", ctypes.c_uint64, 16),
        ("src_csize_or_src_csize_l16", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 32),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_csize_or_dst_csize_l16", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 32),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("index_csize_l16", ctypes.c_uint64, 16),
        ("index_hsize", ctypes.c_uint64, 32),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("index_start_addr_l32", ctypes.c_uint64, 32),
        ("index_start_addr_h13", ctypes.c_uint64, 13),
        ("reserve", ctypes.c_uint64, 18),
        ("inplace_add", ctypes.c_uint64, 1),
        ("default_lanemask1", ctypes.c_uint64, 32),
        ("default_lanemask2", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_cstride: int
    src_hstride_or_src_csize_h16: int
    dst_cstride: int
    dst_hstride_or_dst_csize_h16: int
    index_cstride: int
    start_point: int
    index_csize_h16: int
    src_csize_or_src_csize_l16: int
    src_hsize: int
    src_wsize: int
    dst_csize_or_dst_csize_l16: int
    dst_hsize: int
    dst_wsize: int
    index_csize_l16: int
    index_hsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    index_start_addr_l32: int
    index_start_addr_h13: int
    reserve: int
    inplace_add: int
    default_lanemask1: int
    default_lanemask2: int

    length: int = 768


class DMA_reverse_reg(atomic_reg):
    OP_NAME = "DMA_reverse"
    _fields_ = [
        ("intr_en", ctypes.c_uint64, 1),
        ("stride_enable", ctypes.c_uint64, 1),
        ("nchw_copy", ctypes.c_uint64, 1),
        ("cmd_short", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 2),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 20),
        ("cmd_type", ctypes.c_uint64, 5),
        ("cmd_special_function", ctypes.c_uint64, 3),
        ("fill_constant_en", ctypes.c_uint64, 1),
        ("src_data_format", ctypes.c_uint64, 4),
        ("reserved", ctypes.c_uint64, 19),
        ("cmd_id_dep", ctypes.c_uint64, 21),
        ("reserved", ctypes.c_uint64, 2),
        ("break_point", ctypes.c_uint64, 1),
        ("reserved", ctypes.c_uint64, 8),
        ("constant_value", ctypes.c_uint64, 32),
        ("src_nstride", ctypes.c_uint64, 32),
        ("src_cstride", ctypes.c_uint64, 32),
        ("src_hstride", ctypes.c_uint64, 32),
        ("src_wstride", ctypes.c_uint64, 32),
        ("dst_nstride", ctypes.c_uint64, 32),
        ("dst_cstride", ctypes.c_uint64, 32),
        ("dst_hstride", ctypes.c_uint64, 32),
        ("dst_wstride", ctypes.c_uint64, 32),
        ("src_nsize", ctypes.c_uint64, 16),
        ("src_csize", ctypes.c_uint64, 16),
        ("src_hsize", ctypes.c_uint64, 16),
        ("src_wsize", ctypes.c_uint64, 16),
        ("dst_nsize", ctypes.c_uint64, 16),
        ("dst_csize", ctypes.c_uint64, 16),
        ("dst_hsize", ctypes.c_uint64, 16),
        ("dst_wsize", ctypes.c_uint64, 16),
        ("src_start_addr_l32", ctypes.c_uint64, 32),
        ("src_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("dst_start_addr_l32", ctypes.c_uint64, 32),
        ("dst_start_addr_h13", ctypes.c_uint64, 13),
        ("reserved", ctypes.c_uint64, 19),
        ("reserved", ctypes.c_uint64, 32),
        ("reserved", ctypes.c_uint64, 32),
        ("default_lanemask1", ctypes.c_uint64, 32),
        ("default_lanemask2", ctypes.c_uint64, 32),
    ]

    intr_en: int
    stride_enable: int
    nchw_copy: int
    cmd_short: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    reserved: int
    cmd_type: int
    cmd_special_function: int
    fill_constant_en: int
    src_data_format: int
    reserved: int
    cmd_id_dep: int
    reserved: int
    break_point: int
    reserved: int
    constant_value: int
    src_nstride: int
    src_cstride: int
    src_hstride: int
    src_wstride: int
    dst_nstride: int
    dst_cstride: int
    dst_hstride: int
    dst_wstride: int
    src_nsize: int
    src_csize: int
    src_hsize: int
    src_wsize: int
    dst_nsize: int
    dst_csize: int
    dst_hsize: int
    dst_wsize: int
    src_start_addr_l32: int
    src_start_addr_h13: int
    reserved: int
    dst_start_addr_l32: int
    dst_start_addr_h13: int
    reserved: int
    reserved: int
    reserved: int
    default_lanemask1: int
    default_lanemask2: int

    length: int = 768


op_class_dic: Dict[str, Type[atomic_reg]] = {
    "sCONV": sCONV_reg,
    "sCONV_DW": sCONV_DW_reg,
    "sPorD": sPorD_reg,
    "sMM2": sMM2_reg,
    "sRQ&sDQ": sRQ_sDQ_reg,
    "sAR": sAR_reg,
    "sSG": sSG_reg,
    "sSGL": sSGL_reg,
    "sCW&sBC": sCW_sBC_reg,
    "sPRNG": sPRNG_reg,
    "sSFU": sSFU_reg,
    "sLIN": sLIN_reg,
    "sREDUCE": sREDUCE_reg,
    "SYS_TR_WR": SYS_TR_WR_reg,
    "sCMP": sCMP_reg,
    "sVC": sVC_reg,
    "SYS": SYS_reg,
    "DMA_tensor": DMA_tensor_reg,
    "DMA_matrix": DMA_matrix_reg,
    "DMA_masked_select": DMA_masked_select_reg,
    "DMA_general": DMA_general_reg,
    "DMA_nonzero": DMA_nonzero_reg,
    "sDMA_sys": sDMA_sys_reg,
    "DMA_gather": DMA_gather_reg,
    "DMA_scatter": DMA_scatter_reg,
    "DMA_reverse": DMA_reverse_reg,
}
