blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://tpumlir.org/
    about: Quick Start, Technical Reference Manual and tutorials.
  - name: 💬 Q&A / Discussion
    url: https://github.com/sophgo/tpu-mlir/discussions
    about: Ask usage questions or share ideas with the community.
