#!/usr/bin/env python3
"""Generate PCH header from source includes.

Scans .cpp and .h files in Tpu/Top/TopToTpu directories, extracts all
mlir/, llvm/, and C++ STL headers, outputs a single PCH header.

Usage: python3 python/tools/gen_pch_header.py [project_root] > include/tpu_mlir/pch.h
"""

import glob
import os
import re
import sys

LIB_DIRS = [
    "lib/Dialect/Top",
    "lib/Dialect/Tpu",
    "lib/Conversion/TopToTpu",
]

INCLUDE_RE = re.compile(r'\s*#\s*include\s+([<"])([^">]+)[">]')


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else os.getcwd()
    mlir_headers = set()
    llvm_headers = set()
    stl_headers = set()

    for d in LIB_DIRS:
        for pattern in ("**/*.cpp", "**/*.h"):
            for src in glob.glob(os.path.join(root, d, pattern), recursive=True):
                try:
                    with open(src, encoding='utf-8') as f:
                        for line in f:
                            m = INCLUDE_RE.match(line)
                            if not m:
                                continue
                            delim, h = m.group(1), m.group(2)
                            if h.startswith("mlir/"):
                                mlir_headers.add(h)
                            elif h.startswith("llvm/"):
                                llvm_headers.add(h)
                            elif delim == '<' and '/' not in h and not h.endswith(".h"):
                                stl_headers.add(h)
                except IOError:
                    continue

    print("// Auto-generated by python/tools/gen_pch_header.py — do not edit.")
    print("// Regenerate: python3 python/tools/gen_pch_header.py > include/tpu_mlir/pch.h")
    print("#pragma once")
    print()
    print("// C++ STL")
    for h in sorted(stl_headers):
        print(f"#include <{h}>")
    print()
    print("// LLVM")
    for h in sorted(llvm_headers):
        print(f'#include "{h}"')
    print()
    print("// MLIR")
    for h in sorted(mlir_headers):
        print(f'#include "{h}"')


if __name__ == "__main__":
    main()
