// Auto-generated function type enum
// DO NOT EDIT - Generated by /workspace/tpu-mlir/lib/PplBackend/gen_header.sh

#ifndef PPL_DYN_FW_H
#define PPL_DYN_FW_H
#include <stddef.h>
#include <stdint.h>

#define PPL_FW_LAYER_START 10000
typedef enum ppl_fw_layer_type {
  PPL_FW_ADD_CONST = PPL_FW_LAYER_START,
  PPL_FW_FLASH_ATTENTION = 10001,
  PPL_FW_FLASH_ATTENTION_HEIGH_PRECISION = 10002,

  PPL_FW_LAYER_TYPE_UNKNOWN,
} PPL_FW_LAYER_TYPE_T;
// func map
static int ppl_func_map_inited = 0;
static void *ppl_local_func_map[PPL_FW_LAYER_TYPE_UNKNOWN] = {NULL};
static void *ppl_global_func_map[PPL_FW_LAYER_TYPE_UNKNOWN] = {NULL};

#define __DYNAMIC_FUNC_BIND_MAP(m, t, v) m##_map[(t)] = (v)

#define LOCAL_FUNC_BIND(t, v) __DYNAMIC_FUNC_BIND_MAP(ppl_local_func, t, v)
#define GLOBAL_FUNC_BIND(t, v) __DYNAMIC_FUNC_BIND_MAP(ppl_global_func, t, v)

void fw_init_ppl_func_map();
#endif
